artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset_id: spscientist/students-performance-in-exams
  dataset_path: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_ingestion/train_data.csv
  test_data_path: artifacts/data_ingestion/test_data.csv
